### ISSUE TITLE
AttributeError: module 'opensmile' has no attribute 'Smail'

### ISSUE THREAD

**Issue by sumhncku** [audeering/opensmile-python#15]
I try the code like below,
`import opensmile

smile = opensmile.Smail(
    feature_set=opensmile.FeatureSet.ComParE_2016,
    feature_level=opensmile.FeatureLevel.Functionals,
)
y = smile.process_file('wav/03a01Fa.wav')`
But get the attributeError,
How can I fix this error?
Thanks.

**Comment by hagenw** [comment]
Hi, you have a small typo. It should be `smile = opensmile.Smile(` not `smile = opensmile.Smail(`.

**Comment by nmehjabin** [comment]
> I try the code like below, `import opensmile
> 
> smile = opensmile.Smail( feature_set=opensmile.FeatureSet.ComParE_2016, feature_level=opensmile.FeatureLevel.Functionals, ) y = smile.process_file('wav/03a01Fa.wav')` But get the attributeError, How can I fix this error? Thanks.

I am having the same problem but for me it says
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 2
      1 import opensmile
----> 2 smile = opensmile.Smile(
      3     feature_set=opensmile.FeatureSet.ComParE_2016,
      4     feature_level=opensmile.FeatureLevel.Functionals,
      5 )

AttributeError: module 'opensmile' has no attribute 'Smile'

**Comment by nmehjabin** [comment]
> I try the code like below, `import opensmile
> 
> smile = opensmile.Smail( feature_set=opensmile.FeatureSet.ComParE_2016, feature_level=opensmile.FeatureLevel.Functionals, ) y = smile.process_file('wav/03a01Fa.wav')` But get the attributeError, How can I fix this error? Thanks.

Hi, I wanted to ask have you ever occurred with this problem where it gives you the same error but the code is right. I would appreciate any help. Thanks.
`import opensmile
smile = opensmile.Smile(
    feature_set=opensmile.FeatureSet.ComParE_2016,
    feature_level=opensmile.FeatureLevel.Functionals,
)
`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 2
      1 import opensmile
----> 2 smile = opensmile.Smile(
      3     feature_set=opensmile.FeatureSet.ComParE_2016,
      4     feature_level=opensmile.FeatureLevel.Functionals,
      5 )

AttributeError: module 'opensmile' has no attribute 'Smile'
`y = smile.process_file('~/Desktop/Harvard\ list\ 01.wav')`

**Comment by hagenw** [comment]
The code should work without error. Could you check which version you are using, e.g.

```python
>>> import opensmile

>>> opensmile.__version__
'2.4.1'
```

**Comment by nmehjabin** [comment]
> > The code should work without error. Could you check which version you are using, e.g.
> > ```python
> > >>> import opensmile
> > 
> > >>> opensmile.__version__
> > '2.4.1'
> > ```
> 
> I get something like this.
`>>> import opensmile
>>> opensmile.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'opensmile' has no attribute '__version__'
`

**Comment by nmehjabin** [comment]
> The code should work without error. Could you check which version you are using, e.g.
> 
> ```python
> >>> import opensmile
> 
> >>> opensmile.__version__
> '2.4.1'
> ```

This is what I get:
` import opensmile
 opensmile.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'opensmile' has no attribute '__version__'`

**Comment by nmehjabin** [comment]
This is what I get. 
`>>> import opensmile
>>> opensmile.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'opensmile' has no attribute '__version__'
`

**Comment by nmehjabin** [comment]
`>>> opensmile.__
opensmile.__annotations__     opensmile.__loader__
opensmile.__class__(          opensmile.__lt__(
opensmile.__delattr__(        opensmile.__name__
opensmile.__dict__            opensmile.__ne__(
opensmile.__dir__(            opensmile.__new__(
opensmile.__doc__             opensmile.__package__
opensmile.__eq__(             opensmile.__path__
opensmile.__file__            opensmile.__reduce__()
opensmile.__format__(         opensmile.__reduce_ex__(
opensmile.__ge__(             opensmile.__repr__()
opensmile.__getattribute__(   opensmile.__setattr__(
opensmile.__gt__(             opensmile.__sizeof__()
opensmile.__hash__()          opensmile.__spec__
opensmile.__init__(           opensmile.__str__()
opensmile.__init_subclass__(  opensmile.__subclasshook__(
opensmile.__le__(             
`

**Comment by nmehjabin** [comment]
I think I having issues with installment. 
At first I did "pip install opensmile".
`Successfully installed opensmile-2.4.2`
Then I tried to do the example from GitHub which is:
`import opensmile
smile = opensmile.Smile(
    feature_set=opensmile.FeatureSet.ComParE_2016,
    feature_level=opensmile.FeatureLevel.Functionals,
)`
I get this error:
`OSError: dlopen(/Users/nadiamehjabin/anaconda3/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib, 0x0006): tried: '/Users/nadiamehjabin/anaconda3/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/nadiamehjabin/anaconda3/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (no such file), '/Users/nadiamehjabin/anaconda3/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
`
I fixed this problem by doing these steps however, it keeps happening again.

1. Start by cloning the source code from GitHub:

git clone https://github.com/audeering/opensmile.git
2. cd opensmile/
3. bash build.sh

These steps solved the problem yesterday but it's happening now. Can you suggest some ideas how should I approach to solve this issue?

Thanks

**Comment by nmehjabin** [comment]
I was having OS error and I had to fix that first. So I have condo environment for arch x64 as I am running on Mac. I think I am having installation problem. 
I did `pip install opensmile`then  when I tried to import opensmile error occurs:
-----------------------------------------------------------------------------------
(env_x86) nadiamehjabin@Nadias-MacBook-Air ~ % python   
Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:10:28) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import opensmile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'opensmile'

**Comment by hagenw** [comment]
`arm64` this indicates you are not on a x64 architecture, but have a M1 Mac. This architecture is not yet supported, compare https://github.com/audeering/opensmile-python/issues/78.

**Comment by nmehjabin** [comment]
How should I set up then? I tried some other way too. But they weren’t
working for me.

**Comment by hagenw** [comment]
The M1 architecture of your Mac is not supported, which means there is no way you can use the software until #78 is implemented on our side. My hope is that we finish this during the next two month.

The alternative would be to compile [opensmile](https://github.com/audeering/opensmile) yourself from sources, but there might also issue reported with that, see https://github.com/audeering/opensmile/issues/61.

**Comment by hagenw** [comment]
Since release 2.5.0 we now support M1. Could you try to update your installation of `opensmile` and try again?

**Comment by zargo-zm** [comment]
> > I try the code like below, `import opensmile
> > smile = opensmile.Smail( feature_set=opensmile.FeatureSet.ComParE_2016, feature_level=opensmile.FeatureLevel.Functionals, ) y = smile.process_file('wav/03a01Fa.wav')` But get the attributeError, How can I fix this error? Thanks.
> 
> ## I am having the same problem but for me it says
> AttributeError Traceback (most recent call last) Cell In[3], line 2 1 import opensmile ----> 2 smile = opensmile.Smile( 3 feature_set=opensmile.FeatureSet.ComParE_2016, 4 feature_level=opensmile.FeatureLevel.Functionals, 5 )
> 
> AttributeError: module 'opensmile' has no attribute 'Smile'

I met the same problem，and I found the code isn't working in Windows system but Linux system. This should be the problem

**Comment by hagenw** [comment]
As the code is working with the Windows version in the Github runners, could you please specify which exact version of Windows you are using, and on which architecture/PC you are running it.

**Comment by xhm12345abcde** [comment]
I met the same problem. it says:
Traceback (most recent call last):
  File "D:\workplace\extractFeatures.py", line 7, in <module>
    smile = opensmile.Smile(
AttributeError: module 'opensmile' has no attribute 'Smile'
i'm using python 3.12 on windows11 amd64
