### ISSUE TITLE
OSError when importing opensmile on MacBook M1 laptop

### ISSUE THREAD

**Issue by Omer80** [audeering/opensmile-python#64]
I installed opensmile in a miniforge3 environment, but when I try to import it I get the following error:
`OSError: dlopen(/Users/omertzuk/miniforge3/envs/tf/lib/python3.8/site-packages/audresample/core/bin/libaudresample.dylib, 0x0006): tried: '/Users/omertzuk/miniforge3/envs/tf/lib/python3.8/site-packages/audresample/core/bin/libaudresample.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))`

Is there a way to make it work on x86_64 architecture?

**Comment by hagenw** [comment]
We currently do not support M1, see also https://github.com/audeering/audresample/issues/21.

But we are planing to add it in the near future.

**Comment by hagenw** [comment]
We have now made a new release of `audresample` supporting MacOS M1 architecture.
Please update `audresample` with:

```bash
$ pip install --upgrade audresample
```
and try again.

**Comment by owuQQQ** [comment]
I tried to upgrade the audresample, but it seems not to work.

I got the following errors:

 dlopen(/Users/yuwang/miniforge3/lib/python3.10/site-packages/audresample/core/bin/macos-intel/libaudresample.dylib, 0x0006): tried: '/Users/yuwang/miniforge3/lib/python3.10/site-packages/audresample/core/bin/macos-intel/libaudresample.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/yuwang/miniforge3/lib/python3.10/site-packages/audresample/core/bin/macos-intel/libaudresample.dylib' (no such file), '/Users/yuwang/miniforge3/lib/python3.10/site-packages/audresample/core/bin/macos-intel/libaudresample.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by hagenw** [comment]
Thanks for reporting again.

What seems strange to me is that it tries to load `macos-intel/libaudresample.dylib`, whereas it should load `macos-m1/libaudresample.dylib`.

Could you post the output of the following two commands:

```python
platform.system()
platform.processor()
```

**Comment by hendryman** [comment]
I have exactly the same problem except "intel" does not show up in my error:

`OSError: dlopen(/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib, 0x0006): tried: '/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (no such file), '/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
`

```
>>> platform.system()
'Darwin'
>>> platform.processor()
'arm'
>>>

```

**Comment by hagenw** [comment]
> I have exactly the same problem except "intel" does not show up in my error:
> 
> `OSError: dlopen(/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib, 0x0006): tried: '/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (no such file), '/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) `
> 
> ```
> >>> platform.system()
> 'Darwin'
> >>> platform.processor()
> 'arm'
> >>>
> ```

We added support for MacOS M1 only with version [1.2.0](https://audeering.github.io/audresample/changelog.html#version-1-2-0-2023-01-27) of `audresample`, please run
```bash
$ pip install --upgrade audresample
```
and try again.

We are catching the case of `'Darwin'` and `'arm'` at https://github.com/audeering/audresample/blob/3cd2bff35a2818698316c466a8d84dc6816014c3/audresample/core/lib.py#L21-L26. In a CI job on our internal M1 runner it does work.

**Comment by hendryman** [comment]
```
pip install --upgrade audresample                                      ✔
Requirement already satisfied: audresample in /opt/homebrew/lib/python3.10/site-packages (1.2.1)
```
Any idea where else the source of the problem could be?

**Comment by hendryman** [comment]
Here's the full error message I get on my MacBook Pro M1 Max:

```
python3 /Users/manuel/opensmile-python/tests/test_smile.py 

Traceback (most recent call last):
  File "/Users/manuel/Dropbox/GitHub/repos/feelingmachine/develop/emo_detect/opensmile-python/tests/test_smile.py", line 11, in <module>
    import opensmile
  File "/opt/homebrew/lib/python3.10/site-packages/opensmile/__init__.py", line 6, in <module>
    from opensmile.core.smile import (
  File "/opt/homebrew/lib/python3.10/site-packages/opensmile/core/smile.py", line 13, in <module>
    from opensmile.core.SMILEapi import (
  File "/opt/homebrew/lib/python3.10/site-packages/opensmile/core/SMILEapi.py", line 23, in <module>
    smileapi = cdll.LoadLibrary(smileapi_path)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib, 0x0006): tried: '/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (no such file), '/opt/homebrew/lib/python3.10/site-packages/opensmile/core/bin/osx/libSMILEapi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by hagenw** [comment]
You are right, we need to provide openSMILE binaries for M1 as well, `audresample` is of cause not enough.
So at the moment we don't support M1 with the Python package of openSMILE and will need to add it.

**Comment by lrjam** [comment]
Anyone got any updates on this? Praying for a fix. TIA!

**Comment by hagenw** [comment]
There are two steps this:

* provide M1 support for the used [audresample](https://audeering.github.io/audresample/) lib, which was done with version 1.3.1
* compile `opensmile` binaries for M1 and include in this repo

The second step requires at the moment that we use internal CI runners to build the required binaries as we did for `audresample`. For `opensmile` this is slightly more complicated and requires certain developers to have time to work on this, which means I cannot directly say when this will be done, but my hope would be that it is solved in the next 3 months.
